# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Product.destroy_all

user1 = User.create({email: "gina@gina.com", name: "Gina", password: "password"})
user2 = User.create({email: "jeff@jeff.com", name: "Jeff", password: "password"})
user3 = User.create({email: "user@user.com", password: "123456", name: "DEMO User"})
user4 = User.create({email: "jacky@jacky.com", password: "password", name: "Jacky"})
user5 = User.create({email: "ben@ben.com", password: "password", name: "Ben"})

products = Product.create([
  {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522966546/bearing-1595147_960_720.png",
    title: "Bearings with Housings-BGSRB624ZZ",
    description: "Direct Mount, Standard with Pilot, Retained",
    quantity: 20, price: 38.62, category: "automation"},
  {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522966545/black_rails.jpg",
    title: "Seating-Bearings BGSRB630ZZ",
    description: "Direct Mount, Standard with Pilot, Retained", price: 38.62, category: "automation"},
  {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522993688/Rotary_Clamp_Cylinders.jpg",
    title: "Clamp Cylinders-MKRCA25-31-R" ,description: "Diameter 25, Stroke 31mm, Rod Tip Shape:	Female Thread",
    quantity: 20, price: 263.77, category: "automation"},
  {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522994089/prna.jpg",
    title: "Small High Rotor/Standard Type, PRNA Series" ,description: "Type: Axis output of rotary actuator on one side, Main Body Shape: Round shape
Angle of Oscillation:90°,Torque(N・m):1～Less than 3 / 3～Less than 6 / 6～Less than 10",
    quantity: 30, price: 165.82, category: "automation"},
  {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522993688/Rotary_Clamp_Cylinders.jpg",
    title: "Rotary Clamp Cylinders-MKRCA50-70-R" ,description: "Diameter 50, Stroke 70mm, Rod Tip Shape:	Female Thread",
    quantity: 5, price: 279.54, category: "automation"},
    {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522966546/bearing-1595147_960_720.png",
      title: "SS Bearing-PGSRB624ZZ",
      description: "Direct Mount, Standard with Pilot, Retained",
      quantity: 20, price: 38.62, category: "automation"},
    {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522966545/black_rails.jpg",
      title: "Heatreated Bearings 624ZZ",
      description: "Direct Mount, Standard with Pilot, Retained", price: 38.62, category: "automation"},
    {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523339263/All_radiation_sensors.jpg",
      title: "radiation_sensors" ,description: "Diameter 25, Stroke 31mm, Rod Tip Shape:	Female Thread",
      quantity: 20, price: 263.77, category: "automation"},
    {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523339263/Digital_Soft_Starter_with_Motor_Protection_and_In_Built_By_Pass.jpg",
      title: "Digital Soft Starter with Motor Protection and In Built By Pass" ,description: "Type: Axis output of rotary actuator on one side, Main Body Shape: Round shape
  Angle of Oscillation:90°,Torque(N・m):1～Less than 3 / 3～Less than 6 / 6～Less than 10",
      quantity: 30, price: 165.82, category: "automation"},
    {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523339263/leuze_mlc500t30-150_3_6.jpg",
      title: "Linear motion sensor-MKR50-70-R" ,description: "Motion sensors stand guard, ready to react to various situations, such as movement in your living room, windows or doors being opened or closed, or a broken window.",
      quantity: 5, price: 279.54, category: "automation"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523603290/SA300.jpg",
        title: "Asco 3/4' Brass 2-Way Normally Closed 120V Solenoid Valve",
        description: "Max Operating Pressure: 150 PSI, AC/DC: AC, Body Material: Brass, Inlet Pipe Size: 3/4, Max Fluid Temperature: 180° F
Orifice Size: 3/4", price: 99.96, category: "automation"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523603757/DSL101.jpg",
        title: "DSL101 Solenoid Valve" ,description: "Poppet Type - 2-Way Solenoid Valve for Size 10, 2-way Cavity",
        quantity: 20, price: 50.00, category: "automation"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1523603290/800px-Drago12P_68HC12_EVB.jpg",
        title: "Programable logic controller" ,description: "PLCs are intended-for and therefore tolerant-of more severe conditions (such as dust, moisture, heat, cold), while offering extensive input/output (I/O) to connect the PLC to sensors and actuators.",
        quantity: 20, price: 563.77, category: "automation"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1522966546/f329cf78bfb93163da3171e2466263a0.jpg",
        title: "Miniature Linear Guide - Wide Rails- Wide Block" ,description: "Radial clearances and accuracies are not guaranteed if the blocks and rails are interchanged from the original set combinations.",
        quantity: 30, price: 35.82, category: "automation"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/cable_carrier.jpg",
        title: "cable carrier MPSPS2550-50-9-S" ,description: "Nylon 6 + Glass Fiber 30%, (Operating Temperature -10 ~ 80°C), Flammability Standard UL94-HB Equivalent",
        quantity: 20, price: 44.99, category: "automation"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/single-linear_unit.jpg",
        title: "Single Axis Robots RS306B-C1-C-5-150-c",
        description: "Instruction Manual (CD-ROM), Power Connector, Dummy Connector",
        quantity: 20, price: 1408.49, category: "automation"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/Electrak_Actuator.jpg",
        title: "Electrak Rod Style Actuator DE12-17W41-08FNHHN",
        description: "Overload clutch for mid and end of stroke protection, Stainless steel extension tube",
        quantity: 20, price: 190.37, category: "automation"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/SKF-Ball-Screw-Repai1D4F97.jpg",
        title: "Rolled Ball Screws FBSSRCA1210-200-G15-Q8-K15",
        description: "Rolled Ball Screws suitable for transfer application",
        quantity: 20, price: 130.78, category: "automation"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/laser-connector.jpg",
        title: "Fiber Collimator VFC-W100" ,description: "Please use when the light from the FC fiber with connector turn into parallel light. The lenses have been subjected to the visible anti-reflection coating.",
        quantity: 30, price: 400.52, category: "automation"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/laser-power-supply.jpg",
        title: "Laser pointer power supply VAOS-AC5V" ,description: "Power supply for VAOS. Check the adaptation model for details. For safety reasons, when the power is ON the monitor lamp lights.",
        quantity: 20, price: 101, category: "automation"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257248/cctv.jpg",
        title: "cctv lenses LCV35",
        description: "Lenses Applicable for use of Narrow Range Examinations in Close-up.",
        quantity: 20, price: 184.64, category: "automation"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/motorize_linearball.jpg",
        title: "[Motorized] X-Axis - Linear Ball XCVL650-2-3-MA-M",
        description: "Have high rigidity and are compact in width. Support 30~75mm of travel distance.",
        quantity: 20, price: 2258.18, category: "automation"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/touch_switch.jpg",
        title: "Ultra small size high-precision PT-touch switch PT PT5M1WB",
        description: "[Stainless Steel] 303 Stainless Steel",
        quantity: 20, price: 75.73, category: "automation"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/Socket_Screws.jpg",
        title: "Socket Head Cap Screws CB4-8",
        description: "4137 Alloy Steel, Black oxide coating, length 8mm, M4",
        quantity: 20, price: 0.22, category: "fasteners"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/Socket_Screws.jpg",
        title: "Socket Head Cap Screws CB4-10",
        description: "4137 Alloy Steel, Black oxide coating, length 10mm, M4",
        quantity: 20, price: 0.22, category: "fasteners"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/Socket_Screws.jpg",
        title: "Socket Head Cap Screws CB4-12",
        description: "4137 Alloy Steel, Black oxide coating, length 12mm, M4",
        quantity: 20, price: 0.22, category: "fasteners"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/anchor_bolt.jpg",
        title: "Stainless Steel Straight Anchor WF-016",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 6 x 45 mm",
        quantity: 20, price: 3.26, category: "fasteners"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/anchor_bolt.jpg",
        title: "Stainless Steel Straight Anchor WF-017",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 8 x 50 mm",
        quantity: 20, price: 3.26, category: "fasteners"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/anchor_bolt.jpg",
        title: "Stainless Steel Straight Anchor WF-018",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 10 x 60 mm",
        quantity: 20, price: 3.26, category: "fasteners"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/anchor_bolt.jpg",
        title: "Stainless Steel Straight Anchor WF-019",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 12 x 80 mm",
        quantity: 20, price: 3.26, category: "fasteners"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/blakc_nut.jpg",
        title: "Flanged Nut with Serrations FNTSL-ST-M4",
        description: "M4 nut",
        quantity: 20, price: 0.15, category: "fasteners"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/blakc_nut.jpg",
        title: "Flanged Nut with Serrations FNTSL-ST-M6",
        description: "M6 nut",
        quantity: 20, price: 0.15, category: "fasteners"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526257247/blakc_nut.jpg",
        title: "Flanged Nut with Serrations FNTSL-ST-M8",
        description: "M8 nut",
        quantity: 20, price: 0.15, category: "fasteners"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/angle-exturde.jpg",
        title: "Angles - Extruded LRA6-A20-B20-L50",
        description: "Economically priced Aluminum Angle configurable in height, width and plate thickness",
        quantity: 20, price: 9.02, category: "materials"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/angle-exturde.jpg",
        title: "Angles - Extruded LRA6-A20-B20-L1002",
        description: "Economically priced Aluminum Angle configurable in height, width and plate thickness",
        quantity: 20, price: 16.28, category: "materials"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Urethane-Wipers.jpg",
        title: "Urethane Sheets UTL2-10",
        description: "Material excellent in mechanical strength and used for generic purposes",
        quantity: 20, price: 3.13, category: "materials"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Urethane-Wipers.jpg",
        title: "Antistatic Urethane Sheets UTLA2-10",
        description: "Material excellent in mechanical strength and used for generic purposes",
        quantity: 20, price: 5.23, category: "materials"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Resin_Rods_-_Transparent.jpg",
        title: "Resin Rods - Transparent RDJA6-100",
        description: "Transparent Acrylic, Polycarbonate Rod.",
        quantity: 20, price: 3.32, category: "materials"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Resin_Rods_-_Transparent.jpg",
        title: "Resin Rods - Transparent RDJA8-100",
        description: "Transparent Acrylic, Polycarbonate Rod.",
        quantity: 20, price: 3.32, category: "materials"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Resin_Rods_-_Transparent.jpg",
        title: "Resin Rods - Transparent RDJA10-100",
        description: "Transparent Acrylic, Polycarbonate Rod.",
        quantity: 20, price: 4.32, category: "materials"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Resin_Rods_-_Transparent.jpg",
        title: "Resin Rods - Transparent RDJA12-100",
        description: "Transparent Acrylic, Polycarbonate Rod.",
        quantity: 20, price: 4.32, category: "materials"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/square-pipe.jpg",
        title: "Aluminum, Angular Pipe (B2 Anodized) AK20201",
        description: "Material, 6063 Aluminum Alloy, width 20mm, height 20mm thinkness 1.5mm",
        quantity: 20, price: 12.3, category: "materials"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/square-pipe.jpg",
        title: "Aluminum, Angular Pipe (B2 Anodized) AK15251",
        description: "Material, 6063 Aluminum Alloy, width 15mm, height 25mm thinkness 1.5mm",
        quantity: 20, price: 12.3, category: "materials"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/PRC03_Series_One_Touch_Lock_Type_Connector.jpg",
        title: "PRC03 Series One Touch Lock Type Connector",
        description: "Easily detachable push-pull one-touch PRC03 connector. Will not be loosened by vibrations and shocks.",
        quantity: 20, price: 9.45, category: "wiring"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353459/Screw-Lock_Plug.jpg",
        title: "BNC Solder/Screw-Lock Plug 050-1363N",
        description: "BNC plug (male) for connecting the center conductor and contact of the commonly used coaxial cable with solder",
        quantity: 20, price: 17.44, category: "wiring"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353459/MDR-Connector_Complete.jpg",
        title: "MDR-Connector Complete Set ",
        description: "Reduces selection labor! Connector and connector hood are sold as a set",
        quantity: 20, price: 16.94, category: "wiring"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353459/wiring1.jpg",
        title: "FANC/CS110 CC-Link",
        description: "FANC uses a sheath with excellent oil-resistance and is suitable for environments with high likelihood of machining oil and lubricant.",
        quantity: 20, price: 171.35, category: "wiring"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353459/Heat_shrinkable_tube_TFN21_series.jpg",
        title: "Heat shrinkable tube TFN21 series",
        description: "The flame-retardant polyolefin product is thin, with excellent flexibility and chemical resistance.",
        quantity: 20, price: 175.91, category: "wiring"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/blue-heat-tube.jpg",
        title: "Heat shrinkable tube TC26 series",
        description: "This is a polyolefin product that is thin with good flexibility.",
        quantity: 20, price: 59.54, category: "wiring"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/black-tubing.jpg",
        title: "General purpose heat shrink tube",
        description: "Eco series flame retardant and flexible thermoplastic shrinkable tube with a shrinkage ratio of 2:1.",
        quantity: 20, price: 9.8, category: "wiring"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353459/Hexagon_Male-Female_Spacer1.jpg",
        title: "Hexagon Male-Female Spacer",
        description: "Male and female hexagon spacer. Free-cutting Brass",
        quantity: 20, price: 1, category: "wiring"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Hexagon_Male-Female_Spacer2.jpg",
        title: "Hexagon Male-Female Spacer - heatreated",
        description: "Male and female hexagon spacer. Free-cutting Brass",
        quantity: 20, price: 0.15, category: "wiring"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Best-desktop-milling-machines-6.jpg",
        title: "Desktop Drilling Machine DPN13B-2",
        description: "The angle and height of the work table can be adjusted.",
        quantity: 20, price: 1223.38, category: "processing"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Drill_Chuck_EA817-6.5.jpg",
        title: "Drill Chuck EA817-6.5",
        description: "Chuck capacity (mm)…0.5 to 6.5",
        quantity: 20, price: 68.86, category: "processing"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Drill_Grinder_Dol-Ken_DL-3.jpg",
        title: "Drill Grinder (Dol-Ken) DL-3",
        description: "Grindstone Diameter 125 mm, Width x Depth x Height 260×210×250mm",
        quantity: 20, price: 1849.7, category: "processing"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/surface_roughness_meter.jpg",
        title: "surface roughfness measure tool",
        description: "measure how smooth~~~~~",
        quantity: 20, price: 1024.24, category: "processing"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Electric_Polisher.jpg",
        title: "Electric Polisher",
        description: "Electronic control type device so rotation rate does not go down even when using heavy loads so high speed and slow speed operation can be switched easily with a button for speed adjustment.",
        quantity: 20, price: 342.75, category: "processing"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Wire_Stripper.jpg",
        title: "Wire Stripper",
        description: " Applicable Range: (Stranded Wire) 0.2 to 6.0 m2. Comes with cutter blade.",
        quantity: 20, price: 13.88, category: "processing"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Screw_Jack.jpg",
        title: "Screw Jack, SJK-50",
        description: "SJK-K type is provided with through holes in the center of the jack, making it possible to fix the jacks using bolts, etc.",
        quantity: 20, price: 35.61, category: "processing"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Digital_Multi-Meter.jpg",
        title: "Digital Multi-Meter MC-01U",
        description: "Rectified true root-mean square (RMS)",
        quantity: 20, price: 149.05, category: "processing"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Air_Plasma_Cutter_IAP50.jpg",
        title: "Air Plasma Cutter IAP50",
        description: "Cutting Capacity / Stainless Steel 0.1~12 mm",
        quantity: 20, price: 4638, category: "processing"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/TIG_Welding_Machin.jpg",
        title: "TIG Welding Machine Light for AC/DC LT201AD",
        description: "Voltage Single-phase 200 / Single-phase 100 (V)",
        quantity: 20, price: 2791, category: "processing"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Unitz_B3000_Series.jpg",
        title: "Unitz B3000 Series",
        description: "DC 4–20 mA (receiver resistance: 100 Ω)",
        quantity: 20, price: 586.63, category: "electrical"},
      {user_id: user4.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353458/Digital_Input_Output.jpg",
        title: "Digital Input/Output DO-32LN-FIT",
        description: "extend board",
        quantity: 20, price: 597.59, category: "electrical"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Buzzer_16_ADP16B4.jpg",
        title: "Buzzer (⌀16) [ADP16B4]",
        description: "Sound Continual",
        quantity: 20, price: 17.35, category: "electrical"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/General-purpose_relay_with_LED_EA940MP-1C.jpg",
        title: "General-purpose relay [with LED] EA940MP-1C",
        description: "Operating ambient temperature--25℃ to 40℃(-25℃ to 55℃ only for -1A to -3A)",
        quantity: 20, price: 37.12, category: "electrical"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353457/Illuminated_Push-button_Switch_Mounting_Hole_%CF%8622.jpg",
        title: "Illuminated Push-button Switch Mounting Hole φ22",
        description: "Economically priced Illuminating, push-button switch. Available in the four colors of red, green, white and yellow.",
        quantity: 20, price: 13.51, category: "electrical"},
      {user_id: user5.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/Single-Phase_Contact.jpg",
        title: "Single-Phase Contact GMC-20P2-AC200V ",
        description: "Compact size and light weight help to minimize installation space.",
        quantity: 20, price: 29.12, category: "electrical"},
      {user_id: user1.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/Electromagnetic_Contactor_without_Case.jpg",
        title: "Electromagnetic Contactor without Case",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 10 x 60 mm",
        quantity: 20, price: 33.18, category: "electrical"},
      {user_id: user3.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/Electromagnetic_Contactor_A.jpg",
        title: "Electromagnetic Contactor 4 port",
        description: "Compatible Drill Diameter 6.4 mm, Thread Diameter×Overall Length 12 x 80 mm",
        quantity: 20, price: 50, category: "electrical"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/Step-Down_Transformer.jpg",
        title: "Step-Down Transformer",
        description: "Primary voltage-100V, Single-phase compound-wound",
        quantity: 20, price: 84.79, category: "electrical"},
      {user_id: user2.id, img_url: "https://res.cloudinary.com/dgxmjwbrc/image/upload/v1526353456/Noise_Filter.jpg",
        title: "Noise Filter (Single-Phase, Low-Profile)",
        description: "Single-Phase Power Line Noise-Penetration Countermeasure",
        quantity: 20, price: 48.64, category: "electrical"}
  ])

  # {user_id: 1, img_url: "./figure this out later", title: "Bearings with Housings-BGSRB624ZZ", description: "Direct Mount, Standard with Pilot, Retained", quantity: 20, price: 12}
